### ISSUE TITLE
Custom categories do not show the name of the category

### ISSUE THREAD

**Issue by kylekthompson** [atareshawty/SpendingTracker#40]
When using a custom category, the name of the category you created is not used. It looks like the id is being used.

![screen shot 2016-01-27 at 12 02 53 pm](https://cloud.githubusercontent.com/assets/6563105/12621320/0a7a3362-c4ee-11e5-88e3-11159e929873.png)

![screen shot 2016-01-27 at 12 02 59 pm](https://cloud.githubusercontent.com/assets/6563105/12621323/0bab697c-c4ee-11e5-866c-8abd18684530.png)

**Comment by atareshawty** [comment]
This happens when the new category is added to the page. When the data populates, the category is found by getting it's value, which is one when added to the dropdown. I changed the value to the category text

**Comment by atareshawty** [comment]
https://github.com/atareshawty/SpendingTracker/pull/45
