### ISSUE TITLE
Big empty space when there is no spending

### ISSUE THREAD

**Issue by atareshawty** [atareshawty/SpendingTracker#44]
When a user signs up and gets logged in for the first time, the profile page has a big blank space due to lack of spending. The canvas (and table) shouldn't be there and there should be a message or something in it's place

<img width="896" alt="screen shot 2016-01-27 at 6 18 45 pm" src="https://cloud.githubusercontent.com/assets/3112926/12631939/6f6d6918-c522-11e5-89e1-892f273c7900.png">

**Comment by kylekthompson** [comment]
Maybe use Primer's [blankslate](http://primercss.io/blankslate/)?

**Comment by atareshawty** [comment]
:+1:  Thanks! That'll look way better than what I was thinking of

**Comment by kylekthompson** [comment]
:bowtie:

**Comment by atareshawty** [comment]
https://github.com/atareshawty/SpendingTracker/pull/49
