### ISSUE TITLE
Income Tracking

### ISSUE THREAD

**Issue by kylekthompson** [atareshawty/SpendingTracker#53]
You should add income tracking to visualize your net spending.

It could be done similarly to how it is now:
- Categories have an additional option when being created (income or expense)
- Color code the categories green or red to show what it is
- Current chart can still be used for expenses
- Add another chart for income
- Add total income amount under the new chart
- Add a net spending somewhere

**Comment by atareshawty** [comment]
Working on it: https://github.com/atareshawty/SpendingTracker/tree/issue53-income-tracking

**Comment by kylekthompson** [comment]
:+1:

**Comment by atareshawty** [comment]
https://github.com/atareshawty/SpendingTracker/pull/62

**Comment by atareshawty** [comment]
How's this, @kylekthompson ?

<img width="1034" alt="screen shot 2016-02-12 at 5 15 39 pm" src="https://cloud.githubusercontent.com/assets/3112926/13021991/5479285e-d1ac-11e5-9d35-0ce195163f64.png">

**Comment by kylekthompson** [comment]
Looks great!
