### ISSUE TITLE
Server side validation

### ISSUE THREAD

**Issue by tarebyte** [atareshawty/SpendingTracker#7]
Right now it appears that you only validation `username` and `password` requirements on the client side.

That's pretty :fearful:

**Comment by atareshawty** [comment]
It's fixed on the db level! https://github.com/atareshawty/SpendingTracker/commit/75f594c986ca6f055818f6c3c83dc123c4daa227
@tarebyte

**Comment by atareshawty** [comment]
The db module I use takes care of sql injection and I added constraints to db which does all error checking needed. Errors are thrown up from the db level and aren't properly handled in controllers yet
