### ISSUE TITLE
Client side validation is really slow

### ISSUE THREAD

**Issue by tarebyte** [atareshawty/SpendingTracker#8]
I have to wait at least 5 seconds for the submit button to update itself so that I can submit a form

**Comment by atareshawty** [comment]
Is that for all submit buttons? @tarebyte

**Comment by tarebyte** [comment]
Just the login form, and signup AFAIK. I actually haven't gotten any further due to the fact my db is messed up.

**Comment by tarebyte** [comment]
![clientside_validation](https://cloud.githubusercontent.com/assets/564113/11531924/4db3a48e-98ce-11e5-84a3-f8fdadac2d4e.gif)

**Comment by atareshawty** [comment]
Fixed!
